# Generated by Django 3.2.21 on 2024-01-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Messages'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('product_inquiry', 'Product Inquiry'), ('order_status', 'Order Status'), ('return_exchange', 'Return/Exchange'), ('payment_issue', 'Payment Issue'), ('technical_support', 'Technical Support'), ('feedback', 'Feedback/Suggestions'), ('other', 'Other')], default='other', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='surname',
            field=models.CharField(default='not-defined', max_length=100),
            preserve_default=False,
        ),
    ]
