# Generated by Django 3.2.21 on 2023-09-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230910_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='taste_notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
