# Generated by Django 3.2.21 on 2023-09-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230910_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clearance',
            field=models.BooleanField(default=False, help_text='Check this if the product is on clearance.'),
        ),
        migrations.AddField(
            model_name='product',
            name='deal',
            field=models.BooleanField(default=False, help_text='Check this if the product is on deal.'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(default=False, help_text='Check this if the product is a new arrival.'),
        ),
    ]
