# Generated by Django 3.2.21 on 2023-09-15 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230910_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alcohol_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.alcoholtype'),
        ),
    ]
