# Generated by Django 3.2.21 on 2023-09-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_alcohol_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='alcohol_type',
        ),
    ]
